kind: pipeline
type: docker
name: MineGuide_CI_Pipeline

trigger:
  branch:
    - develop
  event:
    - push

steps:
  - name: build
    image: hub.codefirst.iut.uca.fr/marc.chevaldonne/codefirst-dotnet7-maui:latest
    commands:
      - cd Sources/
      - dotnet restore MineGuide.sln
      - dotnet build MineGuide.sln -c Release --no-restore
      - dotnet publish MineGuide.sln -c Release --no-restore

  - name: tests
    image: mcr.microsoft.com/dotnet/sdk:7.0
    commands:
      - cd Sources/
      - dotnet restore "MineGuide.sln"
      - dotnet test "MineGuide.sln" --no-restore
    depends_on: [build]